name: clients_app
description: "A new Flutter project."

publish_to: 'none' # Supprimez cette ligne si vous souhaitez publier votre package

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0" # Mise à jour du SDK pour être compatible avec Flutter 3.3+

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_core_web: ^2.10.0
  firebase_messaging: ^14.7.10
  firebase_messaging_web: ^3.5.18
  js: ^0.6.7
  # Géolocalisation pour récupérer la position du client
  geolocator: ^10.1.1 # Mise à jour à la dernière version

  # Utilisation d'OpenStreetMap avec flutter_map
  flutter_map: ^8.1.1

  # Icônes Cupertino
  cupertino_icons: ^1.0.8

  # Requêtes HTTP vers l'API Laravel
  http: ^1.3.0

  # Stockage local (pour sauvegarder le token d'authentification)
  shared_preferences: ^2.2.2

  # Gestion de la base de données SQLite
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.9.1
  flutter_secure_storage: ^9.2.4

  # Dépendance latlong2 (requis pour flutter_map)
  latlong2: ^0.9.1

  # Gestion des permissions (pour la localisation et autres)
  permission_handler: ^11.4.0 # Assure-toi de mettre la dernière version disponible

  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png