// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6NeuqUhRusaCvXlSZAATHefGK7DzLSZw',
    appId: '1:531843061403:web:6429872d7c13675fa3d83e',
    messagingSenderId: '531843061403',
    projectId: 'projet-ec820',
    authDomain: 'projet-ec820.firebaseapp.com',
    storageBucket: 'projet-ec820.firebasestorage.app',
    measurementId: 'G-335D6QBGYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpWPCov-SPWzMbojgPbh5dGojMvxjyPoU',
    appId: '1:531843061403:android:6d68259737fa6d9da3d83e',
    messagingSenderId: '531843061403',
    projectId: 'projet-ec820',
    storageBucket: 'projet-ec820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzmOlDUWmob4W0oQFJuLmFwQIFezAq5AA',
    appId: '1:531843061403:ios:5fa276cb8fa00542a3d83e',
    messagingSenderId: '531843061403',
    projectId: 'projet-ec820',
    storageBucket: 'projet-ec820.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzmOlDUWmob4W0oQFJuLmFwQIFezAq5AA',
    appId: '1:531843061403:ios:5fa276cb8fa00542a3d83e',
    messagingSenderId: '531843061403',
    projectId: 'projet-ec820',
    storageBucket: 'projet-ec820.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6NeuqUhRusaCvXlSZAATHefGK7DzLSZw',
    appId: '1:531843061403:web:02732608a7b54b5ea3d83e',
    messagingSenderId: '531843061403',
    projectId: 'projet-ec820',
    authDomain: 'projet-ec820.firebaseapp.com',
    storageBucket: 'projet-ec820.firebasestorage.app',
    measurementId: 'G-FT55E5PT2X',
  );
}
